server:
  port: 8082

spring:
  shardingsphere:
    datasource: # 数据源配置
      names: ds-0,ds-1 # 数据源名称
      ds-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db1?characterEncoding=utf-8
        username: root
        password: 123456
      ds-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db2?characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      sharding: # 分片配置
        tables:
          tb_order: # 逻辑表名称
            actual-data-nodes: ds-$->{0..1}.tb_order_$->{0..1} # 由数据源名 + 表名组成（参考 Inline 语法规则）
            database-strategy: # 分库策略
              standard:
                sharding-column: id
                sharding-algorithm-name: db-inline
            table-strategy: # 分表策略
              standard:
                sharding-column: id
                sharding-algorithm-name: t-order-inline
        sharding-algorithms: # 分片算法配置
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: tb_order_$->{id % 2}
          db-inline:
            type: INLINE
            props:
              algorithm-expression: ds-$->{id % 2}
    props:
      sql-show: true # 打印sql
