server:
  port: 8083

spring:
  shardingsphere:
    datasource: # 数据源配置
      names: ds-master-one,ds-slave-one,ds-master-sec,ds-slave-sec
      ds-master-one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db1?characterEncoding=utf-8
        username: root
        password: 123456
      ds-slave-one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db1_slave?characterEncoding=utf-8
        username: root
        password: 123456
      ds-master-sec:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db2?characterEncoding=utf-8
        username: root
        password: 123456
      ds-slave-sec:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db2_slave?characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      readwrite-splitting: # 读写分离配置
        data-sources:
          ds-0:
            type: Static
            load-balancer-name: round_robin
            props:
              write-data-source-name: ds-master-one
              read-data-source-names: ds-slave-one
          ds-1:
            type: Static
            load-balancer-name: round_robin
            props:
              write-data-source-name: ds-master-sec
              read-data-source-names: ds-slave-sec
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
      sharding: # 分片配置
        tables:
          tb_order: # 逻辑表名称
            actual-data-nodes: ds-$->{0..1}.tb_order_$->{0..1} # 由数据源名 + 表名组成（参考 Inline 语法规则）
            database-strategy: # 分库策略
              standard:
                sharding-column: id
                sharding-algorithm-name: db-inline
            table-strategy: # 分表策略
              standard:
                sharding-column: id
                sharding-algorithm-name: t-order-inline
          tb_storage: # tb_storage不分库，只配置了简单的读写分离
            actual-data-nodes: ds-0.tb_storage
        sharding-algorithms: # 分片算法配置
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: tb_order_$->{id % 2}
          db-inline:
            type: INLINE
            props:
              algorithm-expression: ds-$->{id % 2}
    props:
      sql-show: true # 打印sql
