server:
  port: 8082

spring:
  shardingsphere:
    datasource: # 数据源配置
      names: ds-master-one,ds-slave-one,ds-master-sec,ds-slave-sec
      ds-master-one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db1?characterEncoding=utf-8
        username: root
        password: 123456
      ds-slave-one:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db1_slave?characterEncoding=utf-8
        username: root
        password: 123456
      ds-master-sec:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db2?characterEncoding=utf-8
        username: root
        password: 123456
      ds-slave-sec:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding_db2_slave?characterEncoding=utf-8
        username: root
        password: 123456
    rules:
      readwrite-splitting: # 读写分离配置
        data-sources:
          ds-order:
            type: Static
            load-balancer-name: round_robin
            props:
              write-data-source-name: ds-master-one
              read-data-source-names: ds-slave-one
          ds-store:
            type: Static
            load-balancer-name: round_robin
            props:
              write-data-source-name: ds-master-sec
              read-data-source-names: ds-slave-sec
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
      sharding: # 分片配置
        tables:
          tb_order:
            actual-data-nodes: ds-order.tb_order
            key-generate-strategy: # 主键生成策略
              column: id # 分布式序列列名称
              key-generator-name: snow # 分布式序列算法名称
          tb_storage:
            actual-data-nodes: ds-store.tb_storage
        key-generators: # 分布式序列策略配置
          snow:
            type: SNOWFLAKE
    props:
      sql-show: true # 打印sql
